steps:
  - name: gcr.io/cloud-builders/git
    args:
      [
        'clone',
        '-b',
        '$_TAG',
        '--single-branch',
        'https://ktmbees:${_GIT_TOKEN_}@github.com/TravelNepalApp/backend.git',
      ]

  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '--build-arg',
        'GITHUB_TOKEN=${_GIT_TOKEN_}',
        '-t',
        'gcr.io/$PROJECT_ID/travelnepalappbackendprod:${TAG_NAME}',
        '--file=Dockerfile-prod',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/travelnepalappbackendprod:${TAG_NAME}']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'travelnepal-backend-prod',
        '--image',
        'gcr.io/$PROJECT_ID/travelnepalappbackendprod:${TAG_NAME}',
        '--region',
        'us-west1',
        '--platform',
        'managed',
        '--max-instances',
        '2',
        '--allow-unauthenticated',
      ]
timeout: 3000s
substitutions:
  _TAG: 'v1.0.0'
